spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.clinic.hospital: DEBUG

jwt:
  secret: BaikushikovTemirlanSecretKeyForJWTTokenGeneration2024
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics